import type { NavItem, Service, Scene, Stat, Feature, CaseStudy, Testimonial, ProcessStep } from "@/types"

export const navItems: NavItem[] = [
  { name: "Home", href: "#home" },
  { name: "Solutions", href: "#solutions" },
  { name: "Services", href: "#services" },
  { name: "Process", href: "#process" },
  { name: "Case Studies", href: "#cases" },
  { name: "Contact", href: "#contact" },
]

export const services: Service[] = [
  {
    id: "consultancy",
    title: "IT Consultancy",
    description: "Strategic technology advisory and enterprise architecture planning to align IT infrastructure with business objectives.",
    icon: "Brain",
    gradient: "from-blue-500/20 to-purple-500/20",
    size: "lg",
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: "development",
    title: "Software Development",
    description: "Custom enterprise software engineering with modern stacks, microservices architecture, and cloud-native solutions.",
    icon: "Code2",
    gradient: "from-cyan-500/20 to-blue-500/20",
    size: "xl",
    colSpan: 2,
    rowSpan: 2,
  },
  {
    id: "data",
    title: "Data Communication",
    description: "Secure high-speed data communication infrastructure and network architecture for global enterprise operations.",
    icon: "Network",
    gradient: "from-purple-500/20 to-pink-500/20",
    size: "sm",
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: "recruitment",
    title: "IT Recruitment",
    description: "Executive search and technical talent acquisition for engineering, product, and leadership positions.",
    icon: "Users",
    gradient: "from-green-500/20 to-emerald-500/20",
    size: "sm",
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: "management",
    title: "Project Management",
    description: "Enterprise-grade project governance, agile transformation, and delivery management for complex programs.",
    icon: "KanbanSquare",
    gradient: "from-orange-500/20 to-amber-500/20",
    size: "md",
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: "support",
    title: "IT Support",
    description: "24/7 enterprise IT support with NOCs, help desks, and managed infrastructure services globally.",
    icon: "HeadphonesIcon",
    gradient: "from-teal-500/20 to-cyan-500/20",
    size: "md",
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: "automation",
    title: "Automation Solutions",
    description: "Intelligent automation including RPA, AI/ML pipelines, workflow automation, and business process optimization.",
    icon: "Zap",
    gradient: "from-yellow-500/20 to-orange-500/20",
    size: "lg",
    colSpan: 2,
    rowSpan: 1,
  },
  {
    id: "support-cs",
    title: "Customer Support",
    description: "Omnichannel customer experience solutions with AI-powered chatbots, voice, and email support systems.",
    icon: "MessageSquare",
    gradient: "from-indigo-500/20 to-purple-500/20",
    size: "md",
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: "digitization",
    title: "Document Digitization",
    description: "Enterprise document management, intelligent scanning, OCR, and digital archiving solutions.",
    icon: "FileText",
    gradient: "from-sky-500/20 to-blue-500/20",
    size: "sm",
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: "backoffice",
    title: "Back Office Processing",
    description: "Finance, HR, and operations back-office outsourcing with SLAs, compliance, and quality assurance.",
    icon: "ClipboardList",
    gradient: "from-violet-500/20 to-purple-500/20",
    size: "sm",
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: "voice",
    title: "Voice Call Center",
    description: "Inbound and outbound voice services with multilingual support, IVR, and quality monitoring.",
    icon: "Phone",
    gradient: "from-red-500/20 to-rose-500/20",
    size: "md",
    colSpan: 1,
    rowSpan: 1,
  },
  {
    id: "nonvoice",
    title: "Non Voice Call Center",
    description: "Email, chat, and social media support with automated ticket management and SLA-driven workflows.",
    icon: "Mail",
    gradient: "from-fuchsia-500/20 to-pink-500/20",
    size: "md",
    colSpan: 1,
    rowSpan: 1,
  },
]

export const scenes: Scene[] = [
  {
    id: "consultancy",
    title: "IT Consultancy",
    subtitle: "Strategic Vision",
    description: "We architect enterprise technology roadmaps that align with your business objectives, ensuring every investment drives measurable outcomes.",
    gradient: "from-blue-500 via-purple-500 to-cyan-500",
    icon: "Brain",
  },
  {
    id: "development",
    title: "Software Development",
    subtitle: "Engineering Excellence",
    description: "From microservices to monoliths, we build scalable, secure, and maintainable software systems that power enterprise operations.",
    gradient: "from-cyan-500 via-blue-500 to-indigo-500",
    icon: "Code2",
  },
  {
    id: "data",
    title: "Data Communication",
    subtitle: "Connected Intelligence",
    description: "High-performance network infrastructure enabling real-time data flow across global enterprise ecosystems.",
    gradient: "from-purple-500 via-pink-500 to-rose-500",
    icon: "Network",
  },
  {
    id: "recruitment",
    title: "IT Recruitment",
    subtitle: "Talent Architecture",
    description: "We identify, attract, and place elite technology talent that drives innovation and accelerates digital transformation.",
    gradient: "from-emerald-500 via-teal-500 to-cyan-500",
    icon: "Users",
  },
  {
    id: "management",
    title: "Project Management",
    subtitle: "Delivery Excellence",
    description: "Enterprise program management with rigorous governance, agile methodologies, and predictable delivery timelines.",
    gradient: "from-orange-500 via-amber-500 to-yellow-500",
    icon: "KanbanSquare",
  },
  {
    id: "automation",
    title: "Automation Solutions",
    subtitle: "Intelligent Operations",
    description: "End-to-end automation of business processes using RPA, AI, and machine learning for operational excellence.",
    gradient: "from-yellow-500 via-orange-500 to-red-500",
    icon: "Zap",
  },
  {
    id: "support",
    title: "Customer Support",
    subtitle: "Always On",
    description: "Omnichannel support solutions that deliver exceptional customer experiences across every touchpoint, 24/7.",
    gradient: "from-indigo-500 via-purple-500 to-violet-500",
    icon: "MessageSquare",
  },
]

export const stats: Stat[] = [
  { value: "500", label: "Projects Delivered", suffix: "+" },
  { value: "100", label: "Enterprise Clients", suffix: "+" },
  { value: "30", label: "Industry Domains", suffix: "+" },
  { value: "24", label: "Support Coverage", suffix: "/7" },
  { value: "99.9", label: "Service Reliability", suffix: "%" },
]

export const features: Feature[] = [
  {
    id: "expertise",
    title: "Enterprise Expertise",
    description: "Decades of collective experience delivering mission-critical solutions for Fortune 500 organizations.",
    icon: "Building2",
  },
  {
    id: "automation",
    title: "Automation First",
    description: "Every solution embeds intelligent automation from day one, reducing costs and accelerating time-to-value.",
    icon: "Zap",
  },
  {
    id: "teams",
    title: "Dedicated Teams",
    description: "Elite engineering squads that integrate seamlessly with your organization and culture.",
    icon: "Users",
  },
  {
    id: "technology",
    title: "Technology Driven",
    description: "Modern tech stack including AI, cloud-native, microservices, and event-driven architectures.",
    icon: "Cpu",
  },
  {
    id: "scalable",
    title: "Scalable Delivery",
    description: "Flexible engagement models that scale from advisory to full-stack implementation and managed services.",
    icon: "TrendingUp",
  },
  {
    id: "global",
    title: "Global Support",
    description: "24/7 multilingual support across all time zones with local presence in 12+ countries.",
    icon: "Globe",
  },
]

export const caseStudies: CaseStudy[] = [
  {
    id: "consulting",
    title: "Digital Core Transformation",
    category: "Technology Consulting",
    description: "Modernized legacy infrastructure for a global bank, reducing operational costs by 40% while improving system reliability to 99.99%.",
    metrics: [
      { label: "Cost Reduction", value: "40%" },
      { label: "System Uptime", value: "99.99%" },
      { label: "Time to Market", value: "60%" },
    ],
    gradient: "from-blue-500/10 to-purple-500/10",
  },
  {
    id: "recruitment",
    title: "Global Talent Engine",
    category: "Recruitment Transformation",
    description: "Built an AI-powered talent acquisition platform that reduced time-to-hire by 65% for a Fortune 500 technology company.",
    metrics: [
      { label: "Time-to-Hire", value: "65%" },
      { label: "Quality Hires", value: "3x" },
      { label: "Cost per Hire", value: "50%" },
    ],
    gradient: "from-emerald-500/10 to-teal-500/10",
  },
  {
    id: "automation-study",
    title: "Intelligent Process Automation",
    category: "Automation Solutions",
    description: "Automated 200+ business processes for a leading insurance provider, saving 150,000+ person-hours annually.",
    metrics: [
      { label: "Processes Automated", value: "200+" },
      { label: "Hours Saved", value: "150K" },
      { label: "ROI", value: "320%" },
    ],
    gradient: "from-orange-500/10 to-red-500/10",
  },
  {
    id: "support-study",
    title: "Omnichannel Support Hub",
    category: "Support Operations",
    description: "Consolidated 12 fragmented support channels into a unified AI-driven platform serving 5M+ customers.",
    metrics: [
      { label: "CSAT Score", value: "94%" },
      { label: "Response Time", value: "< 2m" },
      { label: "Resolution Rate", value: "98%" },
    ],
    gradient: "from-indigo-500/10 to-violet-500/10",
  },
  {
    id: "backoffice-study",
    title: "Back Office Modernization",
    category: "Digital Back Office",
    description: "Transformed finance and HR operations for a multinational retailer, achieving 70% straight-through processing.",
    metrics: [
      { label: "STP Rate", value: "70%" },
      { label: "Cost Savings", value: "$12M" },
      { label: "Processing Time", value: "85%" },
    ],
    gradient: "from-cyan-500/10 to-blue-500/10",
  },
]

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Sarah Chen",
    role: "CTO",
    company: "Morgan Stanley",
    content: "Their enterprise architecture expertise transformed our legacy systems into a modern, scalable platform. The transition was seamless and the results exceeded our expectations.",
    avatar: "https://i.pravatar.cc/150?img=1",
  },
  {
    id: "2",
    name: "James Mitchell",
    role: "VP of Engineering",
    company: "Salesforce",
    content: "The automation solutions they delivered reduced our operational overhead by 60% while improving accuracy. A true partnership that drives measurable business outcomes.",
    avatar: "https://i.pravatar.cc/150?img=3",
  },
  {
    id: "3",
    name: "Elena Rodriguez",
    role: "Head of Digital Transformation",
    company: "JPMorgan Chase",
    content: "They don't just consult — they build. The dedicated team integrated with ours and delivered a world-class platform in record time.",
    avatar: "https://i.pravatar.cc/150?img=5",
  },
  {
    id: "4",
    name: "Michael Park",
    role: "COO",
    company: "Goldman Sachs",
    content: "Their global delivery model and automation-first approach helped us scale operations across 15 countries with consistent quality and compliance.",
    avatar: "https://i.pravatar.cc/150?img=8",
  },
  {
    id: "5",
    name: "Priya Sharma",
    role: "SVP, Technology Operations",
    company: "Accenture",
    content: "Outstanding technical depth combined with enterprise maturity. They understand the complexity of large-scale transformations and deliver accordingly.",
    avatar: "https://i.pravatar.cc/150?img=10",
  },
  {
    id: "6",
    name: "David Thompson",
    role: "Director, IT Strategy",
    company: "Deloitte",
    content: "The recruitment and team building capabilities are exceptional. They helped us hire 200+ engineers in 6 months without compromising on quality.",
    avatar: "https://i.pravatar.cc/150?img=12",
  },
]

export const processSteps: ProcessStep[] = [
  {
    id: "discover",
    title: "Discover",
    description: "Deep discovery sessions to understand your business, technology landscape, and transformation objectives.",
    icon: "Search",
  },
  {
    id: "strategize",
    title: "Strategize",
    description: "Develop a comprehensive roadmap with clear milestones, technology recommendations, and ROI projections.",
    icon: "LineChart",
  },
  {
    id: "build",
    title: "Build",
    description: "Agile development with dedicated squads, continuous integration, and weekly stakeholder demos.",
    icon: "Hammer",
  },
  {
    id: "deploy",
    title: "Deploy",
    description: "Automated deployment pipelines, blue-green releases, and comprehensive monitoring for zero-downtime launches.",
    icon: "Rocket",
  },
  {
    id: "optimize",
    title: "Optimize",
    description: "Continuous performance optimization, cost management, and iterative improvements based on real-time data.",
    icon: "Settings2",
  },
  {
    id: "scale",
    title: "Scale",
    description: "Architect for growth with elastic infrastructure, global expansion support, and operational excellence frameworks.",
    icon: "Expand",
  },
]

export const trustKeywords = [
  "Industry Expertise",
  "Global Delivery",
  "Automation First",
  "Digital Transformation",
  "24/7 Support",
  "Business Process Excellence",
  "AI Powered Operations",
  "Enterprise Security",
  "Cloud Native",
  "Zero Trust Architecture",
]
